### ISSUE TITLE
输出库文件不是经过bable转换过的

### ISSUE THREAD

**Issue by justin-yzx** [waterchestnut/pinyin#1]
建议npm上包最好经过bable转换一下，今天上午踩个小坑的农民工路过，总之谢谢您提供的方案

**Comment by lyfZhixing** [comment]
我也遇到了这个问题了，在ie11中报语法错误，请问您是怎么解决的

**Comment by suruicq** [comment]
> 我也遇到了这个问题了，在ie11中报语法错误，请问您是怎么​​解决的

请问解决了吗

**Comment by justin-yzx** [comment]
> > 我也遇到了这个问题了，在ie11中报语法错误，请问您是怎么​​解决的
> 
> 请问解决了吗

把他项目文件引入到自己工程中，过自己工程的bable配置
