### ISSUE TITLE
汉字 ‘凃’：getFullChars获取为空，getCamelChars能够正确获取T

### ISSUE THREAD

**Issue by ibrahidy** [waterchestnut/pinyin#9]
getCamelChars：
![image](https://github.com/waterchestnut/pinyin/assets/79615947/f741d1ca-af22-4b26-8461-7b5381105e88)
getFullChars：
![image](https://github.com/waterchestnut/pinyin/assets/79615947/12c91da5-fba9-45e8-91cf-85868ff5a141)

**Comment by waterchestnut** [comment]
谢谢，已添加凃的拼音，v0.2.6。
